version: '3.7'
services:

    fakecam:
        image: fakecam
        init: true
        build:
            context: ./
        volumes:
            - ${IMAGE_BACKGROUND}:/src/background-custom:ro
        devices:
            - ${VIDEO_INPUT}:/dev/video0
            - ${VIDEO_OUTPUT}:/dev/video10
        command: ["-b", "background-custom", "--no-foreground",
                  "--webcam-path", "/dev/video0", "--v4l2loopback-path", "/dev/video10"]
